{% set name = "searvey" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oceanmodeling/searvey/archive/v{{ version }}.tar.gz
  sha256: a46373de31ddcd12b8d9b94551a9745336562149f4f0324e19853407b47b3871

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - poetry-core >=1.0.0
  run:
    - python >=3.8
    - beautifulsoup4
    - erddapy
    - geopandas
    - html5lib
    - limits
    - lxml
    - numpy
    - pandas
    - pydantic
    - requests
    - shapely
    - tqdm
    - typepigeon
    - xarray

test:
  imports:
    - searvey
    - searvey.coops
    - searvey.ioc
  requires:
    - pytest

about:
  home: https://github.com/oceanmodeling/searvey
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Sea state observational data retrieval

  description: |
    Searvey aims to provide near real time observational data related to sea state.
    Data analysis/clean up to facilitate comparison with numerical models.
    On demand data retrieval from multiple sources.
  doc_url: https://searvey.readthedocs.io/
  dev_url: https://github.com/oceanmodeling/searvey

extra:
  recipe-maintainers:
    - zacharyburnett
    - pmav99
    - brey
