{% set name = "searvey" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oceanmodeling/searvey/archive/v{{ version }}.tar.gz
  sha256: f8b604ca4d0c3b09f63e5421051414666ca0ee5465fe8c5fb15584f4194291d9

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - poetry-core <=1.6.0
    - poetry-dynamic-versioning
  run:
    - python >=3.8
    - beautifulsoup4
    - dataretrieval >=1.0.0
    - erddapy
    - geopandas
    - html5lib
    - limits
    - lxml
    - numpy
    - pandas
    - pydantic
    - requests
    - shapely
    - tqdm
    - typing_extensions
    - xarray

test:
  requires:
    - pip
    - pytest
  imports:
    - searvey
    - searvey.coops
    - searvey.ioc
    - searvey.usgs
  commands:
    - python -c 'import searvey.coops; searvey.coops.get_coops_stations()'
    - python -c 'import searvey.ioc; searvey.ioc.get_ioc_stations()'
    - python -c 'import searvey.usgs; searvey.usgs.get_usgs_stations()'
    - python -c 'import searvey.stations; searvey.stations.get_stations()'

about:
  home: https://github.com/oceanmodeling/searvey
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Sea state observational data retrieval

  description: |
    Searvey aims to provide near real time observational data related to sea state.
    Data analysis/clean up to facilitate comparison with numerical models.
    On demand data retrieval from multiple sources.
  doc_url: https://searvey.readthedocs.io/
  dev_url: https://github.com/oceanmodeling/searvey

extra:
  recipe-maintainers:
    - SorooshMani-NOAA
    - zacharyburnett
    - pmav99
    - brey
